name: backend-ci-workflow
on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
    paths:
      - 'starter/backend/**'
  
env:
  # Set Python Version
  PYTHON_VERSION: '3.10'

# Jobs defined in the workflow
jobs:
  lintJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: cd starter/backend && pipenv install -d
      - name: Run Lint
        run: cd starter/backend && pipenv run lint


  testJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: cd starter/backend && pipenv install -d
      - name: Run Tests
        run: cd starter/backend && pipenv run test

  buildJob:
    needs: [lintJob, testJob]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: cd starter/backend && pipenv install -d
      - name: Build app using docker
        run: |
          cd starter/backend
          docker build -t backend-app .
      
